DROP TABLE TRACK CASCADE CONSTRAINTS;

DROP TABLE PILOT CASCADE CONSTRAINTS;

DROP TABLE SESSAO CASCADE CONSTRAINTS;

DROP TABLE LAP CASCADE CONSTRAINTS;

DROP TABLE BESTLAP CASCADE CONSTRAINTS;

CREATE TABLE TRACK (
    "id" NUMBER(4) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
    "track_name" VARCHAR2(100) NOT NULL,
    PRIMARY KEY ("id") USING INDEX ENABLE
);

SELECT
    CONSTRAINT_NAME
FROM
    USER_CONSTRAINTS
WHERE
    TABLE_NAME = 'TRACK'
    AND CONSTRAINT_TYPE = 'P';

ALTER TABLE "TRACK" DROP CONSTRAINT SYS_C001121809;

INSERT INTO "TRACK" (
    "track_name"
) VALUES (
    :TRACK_NAME
) RETURNING "id" INTO :RET_0;

ALTER TABLE "TRACK" ADD "id" NUMBER DEFAULT 0 NOT NULL;

ALTER TABLE "TRACK" ADD PRIMARY KEY ("id");

DESCRIBE TRACK;

CREATE TABLE PILOT(
    "id" NUMBER(4)GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
    "name" VARCHAR2(100) NOT NULL,
    "car" VARCHAR2(30) NOT NULL,
    "skin" VARCHAR2(30) NOT NULL,
    "track_id" NUMBER(*, 0),
    PRIMARY KEY ("id") USING INDEX ENABLE,
    FOREIGN KEY("track_id") REFERENCES "RM97796"."TRACK" ("id") ENABLE
);

CREATE TABLE SESSAO (
    "id" NUMBER(4)GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
    "lapsCount" NUMBER(*, 0),
    "duration" NUMBER(*, 0),
    PRIMARY KEY ("id")USING INDEX ENABLE
);

CREATE TABLE LAP (
    "id" NUMBER(4)GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
    "lap" NUMBER(*, 0),
    "car" NUMBER(*, 0),
    "time" NUMBER(*, 0),
    "cuts" NUMBER(*, 0),
    "tyre" VARCHAR(25),
    "sessao_id" INTEGER NOT NULL,
    PRIMARY KEY ("id")USING INDEX ENABLE,
    FOREIGN KEY("sessao_id") REFERENCES "RM97796"."Sessao" ("id") ENABLE
);

CREATE TABLE BESTLAP (
    "lap_car" NUMBER(*, 0),
    "lap_time" NUMBER(*, 0),
    "lap_lap" NUMBER(*, 0)
);